LibTerm version 5.2.2 (1), 23 Jan 2024 at 00:28
Last login: 21 May 2025 at 10:20
iPhone $ git clone https://github.com/Boomchainlab/chonk9k.git
cd chonk9k
git: command not found
iPhone $ name: Build & Deploy chonk9k for iOS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cross-compile for iOS (darwin/arm64)
        run: |
          GOOS=darwin GOARCH=arm64 go build -o chonk9k-ios ./cmd/chonk9k

      - name: Archive binary
        run: tar czvf chonk9k-ios.tar.gz chonk9k-ios

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chonk9k-ios-binary
          path: chonk9k-ios.tar.gz

  deploy_to_libterm:
    runs-on: ubuntu-latest
    needs: build_ios
    if: github.event_name == 'workflow_dispatch'  # Manual deploy only
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: chonk9k-ios-binary
          path: ./deploy

      - name: Extract artifact
        run: tar xzvf ./deploy/chonk9k-ios.tar.gz -C ./deploy

      - name: Deploy binary to LibTerm device
        env:
          LIBTERM_SSH_HOST: ${{ secrets.LIBTERM_SSH_HOST }}
          LIBTERM_SSH_USER: ${{ secrets.LIBTERM_SSH_USER }}
          LIBTERM_SSH_KEY: ${{ secrets.LIBTERM_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$LIBTERM_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no ./deploy/chonk9k-ios "$LIBTERM_SSH_USER@$LIBTERM_SSH_HOST:~/"
          ssh -o StrictHostKeyChecking=no "$LIBTERM_SSH_USER@$LIBTERM_SSH_HOST" "chmod +x ~/chonk9k-ios"

: command not found

: command not found
name:: [main]
: No match
iPhone $ 
