name: CHONK9K CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  call-node-workflow:
    uses: Boomchainlab/.github/.github/workflows/node-ci.yml@main
    with:
      node_version: '["24.0.1", "22.15.0"]'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
