name: Deploy & Test on Tenderly Fork

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Compile Contracts
        run: npx hardhat compile

      - name: Deploy to Tenderly Fork
        env:
          TENDERLY_FORK_ID: ${{ secrets.TENDERLY_FORK_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          npx hardhat run scripts/deploy.ts --network tenderly > deployed-address.txt
          echo "::set-output name=contract_address::$(grep 'deployed at:' deployed-address.txt | awk '{print $4}')"

      - name: Run Tenderly Simulation (Optional)
        env:
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
        run: |
          echo "Simulating multicall action via Tenderly API..."
          # Insert Tenderly API simulation commands here as needed

      - name: Run Unit Tests
        run: npx hardhat test
